name: Test

on:
  pull_request:
  push:
    branches:
      - master
    tags:
  schedule:
    # Run everyday at 02:34 UTC
    - cron: 34 2 * * *

jobs:
  test:
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    services:
      nsqd:
        image: nsqio/nsq
        options: --entrypoint /nsqd
        ports:
          - 4150:4150
          - 4151:4151
    strategy:
      matrix:
        os:
          - Ubuntu
        python-version:
          - 3.6
          - 3.7
          - 3.8
    env:
      PY_COLORS: 1
      PYTEST_ADDOPTS: --cov-report=xml
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: python -m pip install tox-gh-actions
      - name: Prepare test environment
        run: tox --notest
      - name: Test
        run: tox
      - name: Start SSH via Ngrok
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          USER_PASS: ${{ secrets.SSH_NGROK_USER_PASS }}
      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 1h # Prevent to killing instance after failure
